<a href="https://colab.research.google.com/github/Pheonix1795/MDS_LAB/blob/main/MDS_WEEK2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Indexing NumPy Arrays

In [1]:
import numpy as np

print("--- Indexing ---")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Original array: {arr}")

# Accessing a single element
print(f"Element at index 0: {arr[0]}")

# Accessing elements from a 2D array
arr_2d = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(f"\nOriginal 2D array:\n{arr_2d}")
print(f"Element at row 0, column 1: {arr_2d[0, 1]}")
print(f"Element at row 2, column 0: {arr_2d[2, 0]}")

# Boolean indexing
print(f"Elements greater than 5: {arr[arr > 5]}")

--- Indexing ---
Original array: [1 2 3 4 5 6 7 8 9]
Element at index 0: 1

Original 2D array:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Element at row 0, column 1: 11
Element at row 2, column 0: 16
Elements greater than 5: [6 7 8 9]


## 2. Slicing NumPy Arrays

In [2]:
import numpy as np

print("--- Slicing ---")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Original array: {arr}")

# Slice from index 2 to 5 (exclusive of 5)
print(f"Slice from index 2 to 5: {arr[2:5]}")

# Slice from the beginning to index 4 (exclusive of 4)
print(f"Slice from beginning to index 4: {arr[:4]}")

# Slice from index 6 to the end
print(f"Slice from index 6 to end: {arr[6:]}")

# Slice with step
print(f"Slice with step 2: {arr[::2]}")

arr_2d = np.array([[10, 11, 12, 13], [14, 15, 16, 17], [18, 19, 20, 21]])
print(f"\nOriginal 2D array:\n{arr_2d}")
# Slice rows and columns
print(f"Slice rows 0-1, columns 1-2:\n{arr_2d[0:2, 1:3]}")

--- Slicing ---
Original array: [ 1  2  3  4  5  6  7  8  9 10]
Slice from index 2 to 5: [3 4 5]
Slice from beginning to index 4: [1 2 3 4]
Slice from index 6 to end: [ 7  8  9 10]
Slice with step 2: [1 3 5 7 9]

Original 2D array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Slice rows 0-1, columns 1-2:
[[11 12]
 [15 16]]


## 3. Reshaping NumPy Arrays

In [3]:
import numpy as np

print("--- Reshaping ---")
arr = np.arange(12) # Create an array from 0 to 11
print(f"Original array: {arr}")

# Reshape to 3 rows, 4 columns
arr_reshaped = arr.reshape(3, 4)
print(f"Reshaped to 3x4:\n{arr_reshaped}")

# Reshape to 2 rows, 6 columns
arr_reshaped_2 = arr.reshape(2, 6)
print(f"Reshaped to 2x6:\n{arr_reshaped_2}")

# Flatten an array (convert to 1D)
arr_flat = arr_reshaped.flatten()
print(f"Flattened array: {arr_flat}")

--- Reshaping ---
Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x6:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 4. Joining NumPy Arrays

In [4]:
import numpy as np

print("--- Joining Arrays ---")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")

# Concatenate along axis 0 (rows) - for 1D arrays, it's just concatenation
arr_joined_1d = np.concatenate((arr1, arr2))
print(f"Concatenated 1D: {arr_joined_1d}")

arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
print(f"\nArray 3:\n{arr3}")
print(f"Array 4:\n{arr4}")

# Concatenate along axis 0 (rows)
arr_joined_rows = np.concatenate((arr3, arr4), axis=0)
print(f"Concatenated along axis 0 (rows):\n{arr_joined_rows}")

# Concatenate along axis 1 (columns)
arr_joined_cols = np.concatenate((arr3, arr4), axis=1)
print(f"Concatenated along axis 1 (columns):\n{arr_joined_cols}")

# Stacking vertically (vstack)
arr_vstacked = np.vstack((arr3, arr4))
print(f"Vertically stacked (vstack):\n{arr_vstacked}")

# Stacking horizontally (hstack)
arr_hstacked = np.hstack((arr3, arr4))
print(f"Horizontally stacked (hstack):\n{arr_hstacked}")

--- Joining Arrays ---
Array 1: [1 2 3]
Array 2: [4 5 6]
Concatenated 1D: [1 2 3 4 5 6]

Array 3:
[[1 2]
 [3 4]]
Array 4:
[[5 6]
 [7 8]]
Concatenated along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]
Vertically stacked (vstack):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally stacked (hstack):
[[1 2 5 6]
 [3 4 7 8]]


## 5. Splitting NumPy Arrays

In [5]:
import numpy as np

print("--- Splitting Arrays ---")
arr_to_split = np.arange(16).reshape(4, 4)
print(f"Original array to split:\n{arr_to_split}")

# Split into 2 equal parts horizontally
split_h = np.hsplit(arr_to_split, 2)
print(f"\nHorizontal split (2 parts):")
for i, part in enumerate(split_h):
    print(f"Part {i+1}:\n{part}")

# Split into 4 equal parts vertically
split_v = np.vsplit(arr_to_split, 4)
print(f"\nVertical split (4 parts):")
for i, part in enumerate(split_v):
    print(f"Part {i+1}:\n{part}")

# Split at specific indices (for 1D array)
arr_1d_to_split = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"\nOriginal 1D array to split: {arr_1d_to_split}")
split_at_indices = np.split(arr_1d_to_split, [3, 7]) # Split before index 3 and before index 7
print(f"Split at indices [3, 7]:")
for i, part in enumerate(split_at_indices):
    print(f"Part {i+1}: {part}")

--- Splitting Arrays ---
Original array to split:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Horizontal split (2 parts):
Part 1:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Part 2:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

Vertical split (4 parts):
Part 1:
[[0 1 2 3]]
Part 2:
[[4 5 6 7]]
Part 3:
[[ 8  9 10 11]]
Part 4:
[[12 13 14 15]]

Original 1D array to split: [0 1 2 3 4 5 6 7 8 9]
Split at indices [3, 7]:
Part 1: [0 1 2]
Part 2: [3 4 5 6]
Part 3: [7 8 9]
