<a href="https://colab.research.google.com/github/Pheonix1795/MDS_LAB/blob/main/MDS_WEEK2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Indexing NumPy Arrays

### 1.1 Accessing Single Elements

In [6]:
# Assumes 'arr' is defined in the preceding cell.
print(f"Element at index 0: {arr[0]}")

Element at index 0: 0


### 1.2 Accessing Elements in 2D Arrays

In [7]:
# Assumes 'arr_2d' is defined in the preceding cell.
print(f"Element at row 0, column 1: {arr_2d[0, 1]}")
print(f"Element at row 2, column 0: {arr_2d[2, 0]}")

Element at row 0, column 1: 11
Element at row 2, column 0: 18


### 1.3 Boolean Indexing

In [8]:
# Assumes 'arr' is defined in the preceding cell.
print(f"Elements greater than 5 in 1D array: {arr[arr > 5]}")

Elements greater than 5 in 1D array: [ 6  7  8  9 10 11]


## 2. Slicing NumPy Arrays

### 2.1 Basic 1D Slicing

In [9]:
# Assumes 'arr' is defined in the preceding cell.
print(f"Slice from index 2 to 5: {arr[2:5]}")
print(f"Slice from beginning to index 4: {arr[:4]}")
print(f"Slice from index 6 to end: {arr[6:]}")
print(f"Slice with step 2: {arr[::2]}")

Slice from index 2 to 5: [2 3 4]
Slice from beginning to index 4: [0 1 2 3]
Slice from index 6 to end: [ 6  7  8  9 10 11]
Slice with step 2: [ 0  2  4  6  8 10]


### 2.2 2D Array Slicing

In [10]:
# Assumes 'arr_2d' is defined in the preceding cell.
print(f"Slice rows 0-1, columns 1-2:\n{arr_2d[0:2, 1:3]}")

Slice rows 0-1, columns 1-2:
[[11 12]
 [15 16]]


## 3. Reshaping NumPy Arrays

### 3.1 Reshaping to Specific Dimensions

In [11]:
# Assumes 'arr' is defined in the preceding cell.
arr_reshaped = arr.reshape(3, 4)
print(f"Reshaped to 3x4:\n{arr_reshaped}")
arr_reshaped_2 = arr.reshape(2, 6)
print(f"Reshaped to 2x6:\n{arr_reshaped_2}")

Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x6:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### 3.2 Flattening Arrays

In [12]:
# Assumes 'arr_reshaped' is defined in the preceding sub-section or main cell.
arr_flat = arr_reshaped.flatten()
print(f"Flattened array: {arr_flat}")

Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 4. Joining NumPy Arrays

### 4.1 Concatenation

In [13]:
# Assumes arr1, arr2, arr3, arr4 are defined in the preceding cell.
arr_joined_1d = np.concatenate((arr1, arr2))
print(f"Concatenated 1D (np.concatenate): {arr_joined_1d}")
arr_joined_rows = np.concatenate((arr3, arr4), axis=0)
print(f"Concatenated along axis 0 (rows):\n{arr_joined_rows}")
arr_joined_cols = np.concatenate((arr3, arr4), axis=1)
print(f"Concatenated along axis 1 (columns):\n{arr_joined_cols}")

Concatenated 1D (np.concatenate): [1 2 3 4 5 6]
Concatenated along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]


### 4.2 Stacking

In [14]:
# Assumes arr3, arr4 are defined in the preceding cell.
arr_vstacked = np.vstack((arr3, arr4))
print(f"Vertically stacked (np.vstack):\n{arr_vstacked}")
arr_hstacked = np.hstack((arr3, arr4))
print(f"Horizontally stacked (np.hstack):\n{arr_hstacked}")

Vertically stacked (np.vstack):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally stacked (np.hstack):
[[1 2 5 6]
 [3 4 7 8]]


## 5. Splitting NumPy Arrays

### 5.1 Horizontal Splitting (np.hsplit)

In [15]:
# Assumes 'arr_to_split' is defined in the preceding cell.
split_h = np.hsplit(arr_to_split, 2)
print(f"Horizontal split (2 parts):")
for i, part in enumerate(split_h):
    print(f"Part {i+1}:\n{part}")

Horizontal split (2 parts):
Part 1:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Part 2:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### 5.2 Vertical Splitting (np.vsplit)

In [16]:
# Assumes 'arr_to_split' is defined in the preceding cell.
split_v = np.vsplit(arr_to_split, 4)
print(f"Vertical split (4 parts):")
for i, part in enumerate(split_v):
    print(f"Part {i+1}:\n{part}")

Vertical split (4 parts):
Part 1:
[[0 1 2 3]]
Part 2:
[[4 5 6 7]]
Part 3:
[[ 8  9 10 11]]
Part 4:
[[12 13 14 15]]


### 5.3 Splitting at Specific Indices (np.split)

In [17]:
# Assumes 'arr_1d_to_split' is defined in the preceding cell.
split_at_indices = np.split(arr_1d_to_split, [3, 7]) # Split before index 3 and before index 7
print(f"Split at indices [3, 7]:")
for i, part in enumerate(split_at_indices):
    print(f"Part {i+1}: {part}")

Split at indices [3, 7]:
Part 1: [0 1 2]
Part 2: [3 4 5 6]
Part 3: [7 8 9]
