<a href="https://colab.research.google.com/github/Pheonix1795/MDS_LAB/blob/main/MDS_WEEK2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Indexing NumPy Arrays

### 1.1 Accessing Single Elements

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])      # Output: 10
print("Third element:", arr[2])      # Output: 30
print("Last element:", arr[-1])      # Output: 50
print("Second to last:", arr[-2])    # Output: 40

First element: 10
Third element: 30
Last element: 50
Second to last: 40


### 1.2 Accessing Elements in 2D Arrays

In [ ]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Row 0, Col 0:", matrix[0, 0])  # Output: 1
print("Row 1, Col 2:", matrix[1, 2])  # Output: 6
print("Row 2, Col 1:", matrix[2, 1])  # Output: 8

# Extracting 5, 6, 8, 9 as a matrix
print("\nSub-matrix (5, 6, 8, 9):\n", matrix[1:3, 1:3])

Row 0, Col 0: 1
Row 1, Col 2: 6
Row 2, Col 1: 8

Sub-matrix (5, 6, 8, 9):
 [[5 6]
 [8 9]]


### 1.3 Boolean Indexing

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# Select elements at positions 0, 2, and 4
indices = [0, 2, 4]
print("Selected elements:", arr[indices])  # Output: [10 30 50]

Selected elements: [10 30 50]


## 2. Slicing NumPy Arrays

In [ ]:
# Cell cleared to maintain granular structure.

### 2.1 Basic 1D Slicing

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
# Slice from index 1 to 4
print(arr[1:4])  # [20 30 40]

[20 30 40]


### 2.2 2D Array Slicing

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slice first two rows and first two columns
print(matrix[:2, :2])

[[1 2]
 [4 5]]


## 3. Reshaping NumPy Arrays

In [ ]:
# Cell cleared to maintain granular structure.

### 3.1 Reshaping to Specific Dimensions

In [ ]:
import numpy as np

arr = np.arange(6)
reshaped = arr.reshape(2, 3)
print(reshaped)

[[0 1 2]
 [3 4 5]]


### 3.2 Flattening Arrays

In [ ]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])
print(matrix.flatten())

[1 2 3 4]


### 3.3 Reshaping with an Unknown Dimension (-1)
You can use `-1` for one of the dimensions, and NumPy will automatically calculate the correct value based on the array size.

In [ ]:
import numpy as np

arr = np.arange(12)
# Reshape to 3 rows, and let NumPy decide the number of columns
reshaped = arr.reshape(3, -1)
print("Reshaped with -1:\n", reshaped)
print("Shape:", reshaped.shape)

Reshaped with -1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)


### 3.4 Adding a New Axis (np.newaxis)
Use `np.newaxis` to increase the dimension of your array (e.g., converting a 1D array to a 2D row or column vector).

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

# Convert to column vector
col_vec = arr[:, np.newaxis]
print("Column Vector:\n", col_vec)
print("New Shape:", col_vec.shape)

Column Vector:
 [[1]
 [2]
 [3]]
New Shape: (3, 1)


## 4. Joining NumPy Arrays

In [ ]:
# Cell cleared to maintain granular structure.

### 4.1 Concatenation

In [ ]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))

[1 2 3 4]


### 4.2 Stacking

In [ ]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
print("Vertical:\n", np.vstack((a, b)))
print("Horizontal:", np.hstack((a, b)))

Vertical:
 [[1 2]
 [3 4]]
Horizontal: [1 2 3 4]


## 5. Splitting NumPy Arrays

In [ ]:
# Cell cleared to maintain granular structure.

### 5.1 Horizontal Splitting (np.hsplit)

In [ ]:
import numpy as np

matrix = np.arange(16).reshape(4, 4)
parts = np.hsplit(matrix, 2)
print(parts[0])

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


### 5.2 Vertical Splitting (np.vsplit)

In [ ]:
import numpy as np

matrix = np.arange(16).reshape(4, 4)
parts = np.vsplit(matrix, 2)
print(parts[0])

[[0 1 2 3]
 [4 5 6 7]]


### 5.3 Splitting at Specific Indices (np.split)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
parts = np.split(arr, [2, 4])
print(parts)

[array([1, 2]), array([3, 4]), array([5, 6])]


## 1. Universal Functions (ufuncs)

### Vectorized Arithmetic

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Equivalent to np.add(arr, 5)
print(arr + 5)        # [6 7 8 9 10]

# Equivalent to np.power(arr, 2)
print(arr ** 2)       # [1 4 9 16 25]

# Equivalent to np.negative(arr)
print(-arr)           # [-1 -2 -3 -4 -5]

[ 6  7  8  9 10]
[ 1  4  9 16 25]
[-1 -2 -3 -4 -5]


### Trigonometric & Exponential ufuncs

In [2]:
x = np.array([0, np.pi/2, np.pi])

# Trigonometry
print(np.sin(x))      # [0.000e+00, 1.000e+00, 1.224e-16]

# Exponentials and Logarithms
val = np.array([1, 2, 10])
print(np.exp(val))    # e^x
print(np.log(val))    # Natural log
print(np.log10(val))  # Base-10 log

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[2.71828183e+00 7.38905610e+00 2.20264658e+04]
[0.         0.69314718 2.30258509]
[0.      0.30103 1.     ]


### Advanced Ufunc Features - `reduce`

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
# Reduces using addition: 1 + 2 + 3 + 4 + 5 = 15
print(np.add.reduce(arr))

15


### Advanced Ufunc Features - `accumulate`

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
# Cumulative sum: [1, 1+2, 1+2+3, ...]
print(np.add.accumulate(arr)) # [ 1,  3,  6, 10, 15]

[ 1  3  6 10 15]


### Advanced Ufunc Features - `outer`

In [5]:
import numpy as np
# Creates a 3x3 multiplication table
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(np.multiply.outer(a, b))

[[10 20 30]
 [20 40 60]
 [30 60 90]]


## 2. Mathematical Aggregation Methods

In [6]:
import numpy as np
data = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Full array aggregations
print(np.sum(data))       # 21
print(np.mean(data))      # 3.5
print(np.std(data))       # Standard deviation
print(np.min(data))       # 1
print(np.argmax(data))    # Index of max element (flattened): 5

21
3.5
1.707825127659933
1
5


### Specifying Axes

In [7]:
import numpy as np
data = np.array([[1, 2, 3],
                 [4, 5, 6]])
# Sum along columns (axis=0) -> output shape (3,)
print(data.sum(axis=0))   # [5, 7, 9]

# Sum along rows (axis=1) -> output shape (2,)
print(data.sum(axis=1))   # [6, 15]

[5 7 9]
[ 6 15]


## 3. Handling Missing Data & Comparisons

### Handling NaNs

In [8]:
import numpy as np
arr_with_nan = np.array([1.0, 2.0, np.nan, 4.0])

print(np.sum(arr_with_nan))     # nan
print(np.nansum(arr_with_nan))  # 7.0
print(np.nanmean(arr_with_nan)) # 2.3333...

nan
7.0
2.3333333333333335


### Boolean Logic & Sorting

In [9]:
import numpy as np
x = np.array([10, -5, 20, 0, 15])

# Boolean ufuncs
print(np.abs(x))                 # [10, 5, 20, 0, 15]
print(x > 0)                     # [True, False, True, False, True]

# Any / All checks
print(np.any(x < 0))            # True
print(np.all(x > 0))            # False

# Sorting
print(np.sort(x))                # [-5, 0, 10, 15, 20]
print(np.argsort(x))             # Array of indices that sort x

[10  5 20  0 15]
[ True False  True False  True]
True
False
[-5  0 10 15 20]
[1 3 0 4 2]
