<a href="https://colab.research.google.com/github/Pheonix1795/MDS_LAB/blob/main/MDS_WEEK1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [3]:
import numpy as np
print(np.__version__)

2.0.2


In [4]:
import time
import numpy as np

# Size of the data
size = 1000000

# Python List Performance
list_data = list(range(size))
start_time = time.time()
list_result = [x**2 for x in list_data]
python_time = time.time() - start_time
print(f"Python List time: {python_time:.5f} seconds")

# NumPy Array Performance
numpy_data = np.arange(size)
start_time = time.time()
numpy_result = numpy_data**2
numpy_time = time.time() - start_time
print(f"NumPy Array time: {numpy_time:.5f} seconds")

print(f"\nNumPy is approximately {python_time / numpy_time:.2f}x faster!")

Python List time: 0.07003 seconds
NumPy Array time: 0.00303 seconds

NumPy is approximately 23.10x faster!


In [5]:
import sys
import numpy as np

# Define the number of elements
n = 1000000

# Memory usage for a Python list
# A list stores pointers to objects, so we account for the list overhead plus the size of each integer object
python_list = list(range(n))
list_memory = sys.getsizeof(python_list) + sum(sys.getsizeof(i) for i in python_list)

# Memory usage for a NumPy array
numpy_array = np.arange(n, dtype=np.int64)
# nbytes returns the total bytes consumed by the elements of the array
numpy_memory = numpy_array.nbytes

print(f"Memory used by Python list: {list_memory / (1024**2):.2f} MB")
print(f"Memory used by NumPy array: {numpy_memory / (1024**2):.2f} MB")
print(f"\nNumPy uses approximately {list_memory / numpy_memory:.2f}x less memory!")

Memory used by Python list: 34.33 MB
Memory used by NumPy array: 7.63 MB

NumPy uses approximately 4.50x less memory!


In [6]:
import timeit
import numpy as np

# Configuration
size = 1000000
iterations = 10

# Python List calculation setup
list_data = list(range(size))
def python_sum():
    return sum(list_data)

# NumPy Array calculation setup
numpy_data = np.arange(size)
def numpy_sum():
    return np.sum(numpy_data)

# Run benchmarks
python_time = timeit.timeit(python_sum, number=iterations) / iterations
numpy_time = timeit.timeit(numpy_sum, number=iterations) / iterations

print(f"Average time for Python sum: {python_time:.6f} seconds")
print(f"Average time for NumPy sum:  {numpy_time:.6f} seconds")
print(f"\nNumPy is {python_time / numpy_time:.2f}x faster for summation!")

Average time for Python sum: 0.008012 seconds
Average time for NumPy sum:  0.000418 seconds

NumPy is 19.17x faster for summation!


In [7]:
import numpy as np
import sys
import time

# Configuration
size = 1000000

# 1. MEMORY COMPARISON
list_data = list(range(size))
numpy_data = np.arange(size, dtype=np.int64)

list_mem = sys.getsizeof(list_data) + sum(sys.getsizeof(i) for i in list_data)
numpy_mem = numpy_data.nbytes

print("--- MEMORY USAGE ---")
print(f"Python List: {list_mem / (1024**2):.2f} MB")
print(f"NumPy Array: {numpy_mem / (1024**2):.2f} MB")
print(f"NumPy is {list_mem / numpy_mem:.2f}x more space efficient")

# 2. TIME & PERFORMANCE COMPARISON (Element-wise Operation)
# Python List
start = time.time()
list_res = [x + 2 for x in list_data]
list_time = time.time() - start

# NumPy Array
start = time.time()
numpy_res = numpy_data + 2
numpy_time = time.time() - start

print("\n--- PERFORMANCE (Addition) ---")
print(f"Python List: {list_time:.5f} sec")
print(f"NumPy Array: {numpy_time:.5f} sec")
print(f"NumPy is {list_time / numpy_time:.2f}x faster")

--- MEMORY USAGE ---
Python List: 34.33 MB
NumPy Array: 7.63 MB
NumPy is 4.50x more space efficient

--- PERFORMANCE (Addition) ---
Python List: 0.03957 sec
NumPy Array: 0.00340 sec
NumPy is 11.62x faster


In [9]:
l = [1,2,3,4,5]
type(l)

list

In [19]:
a1 = np.array(l)
print(a1)
type(a1)

[1 2 3 4 5]


numpy.ndarray

In [17]:

a1.dtype

dtype('int64')

In [23]:
a1.size

5

In [25]:
a1.shape

(5,)

In [26]:
a1.nbytes

40

In [27]:
t = (1,2,3,4,5)
print(t)

(1, 2, 3, 4, 5)


In [28]:
type(t)

tuple

In [33]:
t1 = (1,)
print(t1)

(1,)


In [34]:
type(t1)

tuple

In [35]:
a2 = np.array(t)
print(a2)

[1 2 3 4 5]


In [41]:
a2.ndim

1

In [38]:
import numpy as np

# Creating a 2D array (matrix)
a2d = np.array([[1, 2, 3], [4, 5, 6]])

print("2D Array:")
print(a2d)
print(f"\nShape: {a2d.shape}")
print(f"Dimensions: {a2d.ndim}")

2D Array:
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Dimensions: 2


In [43]:
a3 = [[1,2],[3,4]]
matrix = np.array(a3)
print(matrix)

[[1 2]
 [3 4]]


In [44]:
matrix.ndim

2

In [45]:
matrix.shape

(2, 2)

In [47]:
matrix.size

4

In [48]:
matrix.nbytes

32

In [49]:
matrix.flatten()

array([1, 2, 3, 4])

In [52]:
matrix.ravel

<function ndarray.ravel>

In [56]:
a4=np.array([1,2,3,4])
print(a4)

[1 2 3 4]


In [59]:
a5 = np.array([[1,2],[3,4]])
print(a5)

[[1 2]
 [3 4]]


In [62]:
a6 = np.array([[1,2,3],[4,5,6]])
a6 = a6.reshape(3, 2)
print(a6)

[[1 2]
 [3 4]
 [5 6]]


In [63]:
a100 = np.arange(1, 101)
print(a100)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [70]:
a7 = np.arange(0,100,2)
print(a7)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [73]:
a8 = np.arange(100, step=2)
print(a8)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [78]:
matrix1=np.arange(0,10).reshape(2,5)
print(matrix1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [80]:
print(matrix1.flatten)

<built-in method flatten of numpy.ndarray object at 0x7b020b2f9770>


In [89]:
a9 = np.zeros((3, 3),dtype='int')
print(a9)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [92]:
a9 = np.ones((3,3),dtype='int')
print(a9)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [94]:
a9 = np.full((3,3),2)
print(a9)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [98]:
i = np.eye(3,dtype='int')
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
