<a href="https://colab.research.google.com/github/Pheonix1795/MDS_LAB/blob/main/MDS_WEEK2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Indexing NumPy Arrays

### 1.1 Accessing Single Elements

In [32]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])      # Output: 10
print("Third element:", arr[2])      # Output: 30
print("Last element:", arr[-1])      # Output: 50
print("Second to last:", arr[-2])    # Output: 40

First element: 10
Third element: 30
Last element: 50
Second to last: 40


### 1.2 Accessing Elements in 2D Arrays

In [33]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Row 0, Col 0:", matrix[0, 0])  # Output: 1
print("Row 1, Col 2:", matrix[1, 2])  # Output: 6
print("Row 2, Col 1:", matrix[2, 1])  # Output: 8

Row 0, Col 0: 1
Row 1, Col 2: 6
Row 2, Col 1: 8


### 1.3 Boolean Indexing

In [34]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# Select elements at positions 0, 2, and 4
indices = [0, 2, 4]
print("Selected elements:", arr[indices])  # Output: [10 30 50]

Selected elements: [10 30 50]


## 2. Slicing NumPy Arrays

In [36]:
# Cell cleared to maintain granular structure.

### 2.1 Basic 1D Slicing

In [40]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
# Slice from index 1 to 4
print(arr[1:4])  # [20 30 40]

[20 30 40]


### 2.2 2D Array Slicing

In [41]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slice first two rows and first two columns
print(matrix[:2, :2])

[[1 2]
 [4 5]]


## 3. Reshaping NumPy Arrays

In [37]:
# Cell cleared to maintain granular structure.

### 3.1 Reshaping to Specific Dimensions

In [42]:
import numpy as np

arr = np.arange(6)
reshaped = arr.reshape(2, 3)
print(reshaped)

[[0 1 2]
 [3 4 5]]


### 3.2 Flattening Arrays

In [43]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])
print(matrix.flatten())

[1 2 3 4]


## 4. Joining NumPy Arrays

In [38]:
# Cell cleared to maintain granular structure.

### 4.1 Concatenation

In [44]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))

[1 2 3 4]


### 4.2 Stacking

In [45]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
print("Vertical:\n", np.vstack((a, b)))
print("Horizontal:", np.hstack((a, b)))

Vertical:
 [[1 2]
 [3 4]]
Horizontal: [1 2 3 4]


## 5. Splitting NumPy Arrays

In [39]:
# Cell cleared to maintain granular structure.

### 5.1 Horizontal Splitting (np.hsplit)

In [46]:
import numpy as np

matrix = np.arange(16).reshape(4, 4)
parts = np.hsplit(matrix, 2)
print(parts[0])

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


### 5.2 Vertical Splitting (np.vsplit)

In [47]:
import numpy as np

matrix = np.arange(16).reshape(4, 4)
parts = np.vsplit(matrix, 2)
print(parts[0])

[[0 1 2 3]
 [4 5 6 7]]


### 5.3 Splitting at Specific Indices (np.split)

In [48]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
parts = np.split(arr, [2, 4])
print(parts)

[array([1, 2]), array([3, 4]), array([5, 6])]
